import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ScrollProgress } from "./hooks/scrollNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <div className="fixed inset-0 -z-10 bg-[#060e1a] bg-[url('/bg.webp')] bg-cover bg-center" />
         <ScrollProgress/>
        {children}
        </body>
    </html>
  );
}
